export const RECEIVE_MINUTE_DATA = 'RECEIVE_MINUTE_DATA';
export type RECEIVE_MINUTE_DATA = typeof RECEIVE_MINUTE_DATA;

export const RECEIVE_COIN_LIST = 'RECEIVE_COIN_LIST';
export type RECEIVE_COIN_LIST = typeof RECEIVE_COIN_LIST;