export const RECEIVE_MINUTE_DATA = 'RECEIVE_MINUTE_DATA';
export type RECEIVE_MINUTE_DATA = typeof RECEIVE_MINUTE_DATA;

export const RECEIVE_COIN_LIST = 'RECEIVE_COIN_LIST';
export type RECEIVE_COIN_LIST = typeof RECEIVE_COIN_LIST;

export const HANDLE_DRAWER_OPEN = 'HANDLE_DRAWER_OPEN';
export type HANDLE_DRAWER_OPEN = typeof HANDLE_DRAWER_OPEN;

export const HANDLE_DRAWER_CLOSE = 'HANDLE_DRAWER_CLOSE';
export type HANDLE_DRAWER_CLOSE = typeof HANDLE_DRAWER_CLOSE;